apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: release-i-046e0-2c27bc6
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-26
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: release-i-046e0-2c27bc6
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.22"
  managementCluster:
    name: release-i-046e0-2c27bc6
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: release-i-046e0-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-staging-eks-a-test-4cd48989-b29c-48d7-856c-026f07c2a2be-76
  clusterConfigPath: aws-staging-eks-a-test-4cd48989-b29c-48d7-856c-026f07c2a2be-76
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-staging-eks-a-test-4cd48989-b29c-48d7-856c-026f07c2a2be-76.git
  systemNamespace: default

---
